name: Release

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install dependencies
        run: npm ci
      - name: Build App Release
        run: npm run build
      - name: Build Web Release
        run: |
          rm -rf asteroids-web.zip
          cd resources
          zip -r ../asteroids-web.zip .
          cd ..
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: |
            INSTALL.md
            dist/asteroids-release.zip
            asteroids-web.zip
